dist: trusty

notifications:
  email:
    recipients:
      - dev@rocketmq.apache.org
  on_success: change
  on_failure: always

language: java

jdk:
    - oraclejdk8
    - oraclejdk9
    - oraclejdk11
    - openjdk8

# before_install:
#   - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
#   - cat ~/.mavenrc
#   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
#   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi

script:
  - travis_retry mvn -B clean apache-rat:check -debug
  - travis_retry mvn -B clean install jacoco:report coveralls:report
